---

- name: Ensure service group is present
  group:
    name: '{{ smsshell__service_group }}'
    system: true
    state: present
  notify: ['restart-smsshell']

- name: Ensure service user is present
  user:
    name: '{{ smsshell__service_user }}'
    group: '{{ smsshell__service_group }}'
    groups: '{{ smsshell__service_group_users }}'
    append: true
    shell: /sbin/nologin
    home: '{{ smsshell__service_var_directory }}'
    createhome: false
    system: true
    state: present
  notify: ['restart-smsshell']

- name: Ensure required directories exists
  file:
    path: '{{ item }}'
    owner: '{{ smsshell__service_user }}'
    group: '{{ smsshell__service_group }}'
    mode: 0750
    state: directory
  with_items:
    - '{{ smsshell__service_var_directory }}'

- name: Deploy python virtual env
  pip:
    requirements: '{{ smsshell__install_pip_requirements_file }}'
    virtualenv: '{{ smsshell__service_virtual_env_directory }}'
    virtualenv_command: '{{ smsshell__service_virtual_env_command }}'
    state: present
  notify: ['restart-smsshell']

- name: Test if configuration file exists
  stat:
    path: '{{ smsshell__configuration_file_path }}'
  register: _smsshell__configuration_file_stat

- name: Create configuration file
  template:
    src: config_header.j2
    dest: '{{ smsshell__configuration_file_path }}'
    owner: '{{ smsshell__service_user }}'
    group: '{{ smsshell__service_group }}'
    mode: 0640
  when: not _smsshell__configuration_file_stat.stat.exists
  notify: ['restart-smsshell']

- name: Configure options
  ini_file:
    path: '{{ smsshell__configuration_file_path }}'
    section: "{{ item.key.split('.')[0] }}"
    option: "{{ item.key.split('.')[1] }}"
    # until https://github.com/ansible/ansible/issues/29711
    value: "{{ item.value|replace('\n','\n'~(' '*(item.key.split('.')[1]|length + 3))) }}"
    mode: 0600
    state: "{{ 'absent' if item.value is none else 'present' }}"
  with_dict: '{{ smsshell__parameters }}'
  notify: ['restart-smsshell']
