---

- name: Ensure service group is present
  group:
    name:   '{{ smsshell__service_group }}'
    system: yes
    state:  present
  notify: [ 'restart-smsshell' ]

- name: Ensure service user is present
  user:
    name:       '{{ smsshell__service_user }}'
    group:      '{{ smsshell__service_group }}'
    shell:      /sbin/nologin
    home:       '{{ smsshell__service_var_directory }}'
    createhome: no
    system:     yes
    state:      present
  notify: [ 'restart-smsshell' ]

- name: Ensure required directories exists
  file:
    path:  '{{ item }}'
    owner: '{{ smsshell__service_user }}'
    group: '{{ smsshell__service_group }}'
    mode:  0750
    state: directory
  with_items:
    - '{{ smsshell__service_var_directory }}'

- name: Create configuration file
  template:
    src:   config.j2
    dest:  '{{ smsshell__configuration_file_path }}'
    owner: '{{ smsshell__service_user }}'
    group: '{{ smsshell__service_group }}'
    mode:  0640
  notify: [ 'restart-smsshell' ]
