---

- name: Assert required variables
  assert:
    that:
      - smsshell__parameters['main.mode'] in ['DAEMON']
      - smsshell__parameters['daemon.receiver_type'] in ['fifo', 'unix']
      - smsshell__parameters['daemon.message_parser'] in ['json']
      - smsshell__parameters['daemon.transmitter_type'] in ['stdout', 'python_gammu']
      - smsshell__parameters['main.log_level'] in ['ERROR', 'WARN', 'INFO', 'DEBUG', 'INFO']
