---

- name: Install required packages
  package:
    name: '{{ smsshell__packages_names|list }}'
    state: present

- name: Install SMSShell program
  git:
    repo: '{{ smsshell__repository_url }}'
    dest: '{{ smsshell__install_path }}'
    clone: true
    version: '{{ smsshell__repository_version }}'
    update: '{{ smsshell__git_update }}'
    force: true
  notify: ['restart-smsshell']
  tags: ['smsshell-install-git']
