---
# tasks file for smsshell

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works on a platform with systemd'
  when: ansible_service_mgr != 'systemd'
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['smsshell', 'smsshell-install']

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: ['smsshell', 'smsshell-configure']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['smsshell', 'smsshell-service']

- name: Optionally importing facts tasks
  include_tasks: facts.yml
  when: smsshell__facts|bool
  tags: ['smsshell', 'smsshell-facts']
